#!/usr/bin/env bash
 ORANGE="$(printf '\033[33m')" 
WHITE="$(printf '\033[37m')" 

printf " \e[1;37m\n"


cd /root/fgphisher-tool || { echo "Failed to enter the directory => /root/fgphisher-tool"; exit 1; }

fgphisher(){
  case "$1 $2" in
    "-f --help")
      sudo bash camphisher.sh 
      ;;
    "-s --start")
      server 
      ;;
    "-d files.png")
    rm -rf /root/fgphisher-tool/server.phisher/files
      ;;
    *)
      echo "Erro! Unknown command: $1"
      exit 1
      ;;
  esac
}

server(){
  echo "${WHITE}[${ORANGE}INFO${WHITE}] Starting Fgphisher..."
bash cloud.sh
}


fgphisher "$@"
